enum MainReducerActions {
    SHOW_SCHEDULE = 'SHOW_SCHEDULE',
    SET_GROUP_COOKIE = 'SET_GROUP_COOKIE',
    IS_ON_LOGIN = 'IS_ON_LOGIN',
    IS_ONLINE = 'IS_ONLINE',
    UPDATE_SAVED_TIME = 'UPDATE_SAVED_TIME',
    LOAD_SERVICES = 'LOAD_SERVICES',
    SELECT_SERVICE = 'SELECT_SERVICE',
}
